name: "Auto Assign Reviewers"
on:
  pull_request_target:
    branches:
      - 'master'
      - 'main'
      - '202[0-9][0-9][0-9]'

permissions:
  pull-requests: write

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip pyaml PyGithub
      - name: Check Python version
        run: python --version
      - name: List files
        run: ls -al
      - name: Assign reviewers
        run: python .github/.code-reviewers/auto-assign.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          CONTRIBUTOR_FILE: file1.yaml
          CONTRIBUTOR_INDEX: file2.yaml
          
      - name: Cleanup the checked out repo
        run: git clean -fdx
