name: "Auto Assign"
on:
  pull_request:
    branches:
      - 'master'
      - 'main'
      - '202[0-9][0-9][0-9]'

permissions:
  pull-requests: write

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: shufo/auto-assign-reviewer-by-files@v1.2.1
        with:
          config: ".github/assign-by-files.yml"
          token: ${{ secrets.GITHUB_TOKEN }}
